# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

# Move from sqlite3 without crashing
<%
db_host    = ENV.fetch('DB_HOST', ENV.fetch('RICKI-DICRISTOFORO_DB_1_PORT_5432_TCP_ADDR', 'localhost'))
db_port    = ENV['RICKI-DICRISTOFORO_DB_1_PORT_5432_TCP_PORT'] || ENV['DB_PORT'] || 5432
require 'etc'
pool_size =
  # Web: max workers * max threads
  ENV.fetch('WEB_CONCURRENCY', 3).to_i * ENV.fetch('MAX_THREADS', 5).to_i +
  # ActiveJob Async max thread pool size
  Etc.nprocessors
ERB
%>

defaults: &defaults
  adapter: postgresql
  min_messages: WARNING
  pool: <%= pool_size %>
  host: <%= db_host %>
  port: <%= db_port %>
  username: <%= ENV.fetch('DB_USERNAME', 'ricki-dicristoforo_dev').inspect %>
  password: <%= ENV.fetch('DB_PASSWORD', "ricki-dicristoforo").inspect %>
  encoding: utf8

development:
  adapter: sqlite3
  min_messages: WARNING
  pool: <%= pool_size %>
  timeout: 5000
  encoding: utf8
  database: db/development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *defaults
  database: db/test.sqlite3

production:
  <<: *defaults
  encoding: utf8
  min_messages: WARNING
  url: <%= ENV['DATABASE_URL'].inspect if ENV['DATABASE_URL'] %>
  database: <%= 'ricki-dicristoforo_prod' unless ENV['DATABASE_URL'] %>
